name: lower

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  id-token: write

env:
  LANG: en_US.UTF-8

jobs:
  lower-pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v14
      with:
        name: tek
        signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
    - id: bounds
      run: nix run .#lower -- --stabilize --output=ga-pr
    - name: pr
      if: steps.bounds.outputs.commit-message
      uses: peter-evans/create-pull-request@v7
      with: ${{ steps.bounds.outputs }}
